# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_PROPRIETAIRE:       ROLE_PROPRIETAIRE
        ROLE_MEMBRE_SIMPLE: ROLE_MEMBRE_SIMPLE
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN




    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                success_handler: redirect.after.login


            logout:
                target: /login
            anonymous:    true
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/layoutUser, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        #- { path: ^/user/, role: ROLE_USER }
        #- { path: ^/user/, role: ROLE_MEMBRE_PRO }
        #- { path: ^/user/, role: ROLE_MEMBRE_SIMPLE }



            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
