user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_layoutUser:
    path:     /layoutUser
    defaults: { _controller: UserBundle:User:layoutUser }

homeUser:
    path:     /homeUser
    defaults: { _controller: UserBundle:User:homeUser }


dashboardAdmin:
    path:     /dashboardAdmin
    defaults: { _controller: UserBundle:User:dashboardAdmin }

user_layoutAdmin:
    path:     /layoutAdmin
    defaults: { _controller: UserBundle:User:layoutAdmin }

redirect_register:
    path:     /register/confirmed
    defaults: { _controller: UserBundle:User:RedirectRegister}


user_compte:
    path:     /user_compte
    defaults: { _controller: UserBundle:User:compteUser }
user_message:
    path:     /user_message
    defaults: { _controller: UserBundle:User:messageUser }