user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_layoutUser:
    path:     /layoutUser
    defaults: { _controller: UserBundle:User:layoutUser }

form_login:
    path:     /formlogin
    defaults: { _controller: UserBundle:User:form_login }



homeUser:
    path:     /homeUser
    defaults: { _controller: UserBundle:User:homeUser }


dashboardAdmin:
    path:     /dashboardAdmin
    defaults: { _controller: UserBundle:User:dashboardAdmin }

user_layoutAdmin:
    path:     /layoutAdmin
    defaults: { _controller: UserBundle:User:layoutAdmin }

reset:
    path:     /reset
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
